### ISSUE TITLE
[Feature Request] Webhook updates on encrypted imports

### ISSUE THREAD

**Issue by macwille** [methodgg/wago.io#251]
I would like to receive updates from the discord webhook but keep my import password protected.

Currently the webhook only work on public imports. Maybe versioning could be tracked without accessing the encrypted import data?

**Comment by oratory** [comment]
Nothing that the webhook uses is encrypted so that isn't a problem. However webhooks aren't sent for hidden/private/encrypted/restricted imports since the webhook option applies to *all* imports, so stuff that isn't public aren't sent that way.

Adding a separate webhook override option attached to the individual import could work though, I'll look into that this week.

**Comment by macwille** [comment]
thanks that was fast!
